version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edge_app_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
